apiVersion: v1
kind: Service
metadata:
  name: next-japan-service
  namespace: ostad
  labels:
    app: next-japan
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
    name: http
  selector:
    app: next-japan
